ALTER TABLE "orders"
ADD COLUMN IF NOT EXISTS "preparation_started_at" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "packed_at" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "dispatched_at" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "delivered_at" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "estimated_delivery_at" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "eta_last_updated_at" TIMESTAMP WITH TIME ZONE;
