import os
import re
import sys
import json
import urllib.request
import urllib.error
from urllib.parse import urlparse

try:
    from bs4 import BeautifulSoup
    import requests
    from supabase import create_client, Client
except ImportError:
    print("Dependencies missing. Please install them by running:")
    print("pip install beautifulsoup4 requests supabase")
    sys.exit(1)

# Supabase Credentials (pull from env or hardcode for testing)
SUPABASE_URL = os.environ.get("NEXT_PUBLIC_SUPABASE_URL", "YOUR_SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "YOUR_SUPABASE_KEY")

if SUPABASE_URL == "YOUR_SUPABASE_URL":
    print("Please set your SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY environment variables.")
    sys.exit(1)

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# Simple search function (simulating a Google search or utilizing a public search API)
# In a real heavy-duty production environment, you would use SERP API or Google Custom Search API.
def find_food_blogs(keyword="seafood recipes"):
    print(f"[*] Searching for high-value targets related to: '{keyword}'...")
    # Simulated high-DA targets for demonstration purposes. 
    # To avoid getting blocked by Google in this script, we'll hit some known culinary directories or simulate it.
    targets = [
        "https://www.simplyrecipes.com",
        "https://www.thekitchn.com",
        "https://www.bonappetit.com",
        "https://www.delish.com",
        "https://www.food52.com"
    ]
    return targets

def extract_contact_email(url):
    print(f"[*] Scanning {url} for contact emails...")
    try:
        # Respectful scraping with a common User-Agent
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
        response = requests.get(url, headers=headers, timeout=10)
        
        # We also want to check their /contact or /about pages
        contact_urls = [url, f"{url}/contact", f"{url}/about"]
        found_emails = set()
        
        for check_url in contact_urls:
            try:
                res = requests.get(check_url, headers=headers, timeout=5)
                # Regex for standard emails
                emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', res.text)
                for email in emails:
                    # Filter out common false positives
                    if not any(x in email.lower() for x in ['wix', 'sentry', 'example', 'domain', '.png', '.jpg']):
                        found_emails.add(email)
            except Exception:
                continue
                
        return list(found_emails)[0] if found_emails else None
        
    except Exception as e:
        print(f"[!] Could not scan {url}: {str(e)}")
        return None

def inject_to_crm(domain, email, anchor_text="premium seafood online"):
    print(f"[*] Injecting {domain} into Supabase CRM...")
    
    # Check if domain already exists
    response = supabase.table('seo_backlinks').select('*').eq('target_domain', domain).execute()
    if len(response.data) > 0:
        print(f"[!] Domain {domain} already exists in CRM. Skipping.")
        return

    # Insert new prospect
    data, count = supabase.table('seo_backlinks').insert({
        "target_domain": domain,
        "contact_email": email,
        "status": "prospect",
        "domain_authority": 80, # This would ideally hit the Moz API to calculate real DA
        "target_anchor_text": anchor_text,
        "notes": "Autogenerated by OceanExotic SEO Spider."
    }).execute()
    
    print(f"[+] Successfully added {domain} to CRM!")

def main():
    print("=========================================")
    print(" OCEANEXOTIC SEO SPIDER BOT INITIALIZED ")
    print("=========================================")
    
    blogs = find_food_blogs("buy premium seafood")
    
    for url in blogs:
        domain = urlparse(url).netloc.replace('www.', '')
        email = extract_contact_email(url)
        
        if not email:
            email = f"editors@{domain}" # Fallback
            print(f"[-] No explicit email found, defaulting to {email}")
        
        inject_to_crm(domain, email)

    print("=========================================")
    print(" SCRAPING COMPLETE. CRM POPULATED.       ")
    print("=========================================")

if __name__ == "__main__":
    main()
